"use client";
import Link from "next/link";
import { ChevronLeft, ChevronRight, MapPin, Star, BadgeCheck } from "lucide-react";
import { businesses } from "../../data/business";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Autoplay } from "swiper/modules";
import "swiper/css";
import "swiper/css/navigation";
export default function Featured() { const premiumBusinesses = businesses.filter((b) => b.premium).slice(0, 6); return <section className="bg-[#fffdf9] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex items-end justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[.25em] text-[#A94743]">Selección especial</span><h2 className="mt-3 text-4xl font-black text-[#342821]">Emprendimientos Premium</h2><p className="mt-3 text-[#75685f]">Una vitrina especial para los negocios que impulsan Ibarra.</p></div><div className="flex gap-2"><button className="premium-prev grid h-11 w-11 place-items-center rounded-full border border-[#eadbca] bg-white text-[#833B38] hover:bg-[#f4e7d9]" aria-label="Anterior"><ChevronLeft size={20}/></button><button className="premium-next grid h-11 w-11 place-items-center rounded-full border border-[#eadbca] bg-white text-[#833B38] hover:bg-[#f4e7d9]" aria-label="Siguiente"><ChevronRight size={20}/></button></div></div><Swiper modules={[Navigation, Autoplay]} navigation={{ prevEl: ".premium-prev", nextEl: ".premium-next" }} autoplay={{ delay: 3500, disableOnInteraction: false }} spaceBetween={24} slidesPerView={1} breakpoints={{ 900: { slidesPerView: 2 } }} className="mt-10 !pb-4">{premiumBusinesses.map((business) => <SwiperSlide key={business.id}><article className="grid min-h-[310px] overflow-hidden rounded-[28px] border border-[#eadbca] bg-[#f8f1e7] md:grid-cols-[1fr_42%]"><div className="order-2 flex flex-col justify-center p-7 md:order-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#f4e7d9] px-3 py-1 text-xs font-black uppercase tracking-wider text-[#833B38]">Premium</span>{business.verified && <span className="flex items-center gap-1 rounded-full bg-[#e1f0e5] px-3 py-1 text-xs font-bold text-[#39724d]"><BadgeCheck size={14}/> Verificado</span>}</div><h3 className="mt-4 text-3xl font-black text-[#342821]">{business.name}</h3><p className="mt-2 text-sm font-bold text-[#A94743]">{business.category}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#75685f]">{business.description}</p><p className="mt-4 flex items-center gap-2 text-sm text-[#75685f]"><MapPin size={16}/> {business.city}</p><div className="mt-4 flex items-center gap-1 text-[#c6924b]">{[1,2,3,4,5].map((star) => <Star key={star} size={15} fill="currentColor"/>)}<span className="ml-2 text-sm font-bold text-[#75685f]">5.0</span></div><Link href={`/emprendedores/${business.slug}`} className="mt-5 inline-flex w-fit rounded-full bg-[#A94743] px-5 py-3 text-sm font-bold text-white hover:bg-[#8F3F3B]">Ver emprendimiento</Link></div><img src={business.image} alt={business.name} className="order-1 h-64 w-full object-cover md:order-2 md:h-full"/></article></SwiperSlide>)}</Swiper></div></section>; }
