import Header from "../components/layout/Header";
import { supabase } from "../lib/supabase";
import { Tag, CalendarDays, ArrowUpRight, MessageCircle } from "lucide-react";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function PromotionsPublicPage() {
  const { data: promotions } = await supabase.from("promotions").select("id,title,description,image,start_date,end_date,promotion_type,discount,promotion_link,business_id").eq("status", "active").order("created_at", { ascending: false });
  const businessIds = [...new Set((promotions || []).map((promo) => promo.business_id).filter(Boolean))];
  const { data: businesses } = businessIds.length ? await supabase.from("businesses").select("id,name,slug,whatsapp").in("id", businessIds) : { data: [] };
  const businessById = new Map((businesses || []).map((business) => [business.id, business]));
  return (
    <main className="min-h-screen bg-[#f8f1e7]"><Header /><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8">
      <div className="max-w-2xl"><span className="text-xs font-black uppercase tracking-[.25em] text-[#891C20]">Oportunidades locales</span><h1 className="mt-3 text-5xl font-black text-[#342821]">Promociones que vale la pena descubrir</h1><p className="mt-5 text-lg leading-8 text-[#75685f]">Ofertas, experiencias y beneficios publicados por emprendimientos de Ibarra.</p></div>
      {!promotions?.length ? <div className="mt-12 rounded-[28px] border border-dashed border-[#d9c3ad] bg-[#fffdf9] p-16 text-center"><Tag className="mx-auto text-[#891C20]" size={36}/><h2 className="mt-4 text-2xl font-black">Pronto habrá nuevas promociones</h2><p className="mt-2 text-[#75685f]">Vuelve pronto para conocer las ofertas de nuestros emprendimientos.</p></div> : <div className="mt-12 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{promotions.map((promo) => <article key={promo.id} className="overflow-hidden rounded-[28px] border border-[#eadbca] bg-[#fffdf9] shadow-[0_12px_40px_rgba(105,72,45,.08)]">{promo.image ? <img src={promo.image} alt={promo.title} className="h-52 w-full object-cover"/> : <div className="grid h-52 place-items-center bg-[#eadbca] text-[#891C20]"><Tag size={42}/></div>}<div className="p-6"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-[#f4e7d9] px-3 py-1 text-xs font-bold text-[#6f1519]">{promo.promotion_type || "Oferta"}</span>{promo.discount ? <strong className="text-[#891C20]">-{promo.discount}%</strong> : null}</div><h2 className="mt-4 text-2xl font-black">{promo.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#75685f]">{promo.description || "Descubre esta promoción local."}</p><div className="mt-5 flex items-center gap-2 text-sm text-[#75685f]"><CalendarDays size={16}/>{promo.start_date || "Disponible ahora"}</div>{businessById.get(promo.business_id) ? <p className="mt-2 text-sm font-bold text-[#6f1519]">{businessById.get(promo.business_id)?.name}</p> : <p className="mt-2 text-sm font-bold text-[#6f1519]">Emprendimiento local</p>}{(() => { const business = businessById.get(promo.business_id); const phone = business?.whatsapp ? business.whatsapp.replace(/\D/g, "").replace(/^0/, "593") : ""; const message = encodeURIComponent(`Hola, vengo desde Hecho en Ibarra. Vi la promoción ${promo.title}. ¿Está disponible en ${business?.name || "su emprendimiento"}?`); return phone ? <a href={`https://wa.me/${phone}?text=${message}`} target="_blank" rel="noreferrer" className="mt-5 flex items-center justify-center gap-2 rounded-full bg-[#2f9b62] py-3 text-sm font-bold text-white hover:bg-[#267c4f]"><MessageCircle size={17}/> Consultar por WhatsApp</a> : null; })()}{promo.promotion_link ? <a href={promo.promotion_link} target="_blank" rel="noreferrer" className="mt-3 flex items-center justify-center gap-2 rounded-full border border-[#891C20] py-3 text-sm font-bold text-[#891C20] hover:bg-[#f4e7d9]">Ver enlace de la promoción <ArrowUpRight size={16}/></a> : null}</div></article>)}</div>}
    </section></main>
  );
}
