/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import BusinessCard from "../ui/BusinessCard";
import { supabase } from "../../lib/supabase";
const fallback=[{name:"LAMY",category:"Salud y Belleza",description:"Promociones y novedades de LAMY para tu bienestar.",image:"https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900",slug:"lamy",subcategories:["Velas","Perfumes","Bienestar"]},{name:"LAMY",category:"Bienestar",description:"Descubre las novedades y productos disponibles de LAMY.",image:"https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=900",slug:"lamy",subcategories:["Cosmética natural","Sales terapéuticas"]},{name:"Próximamente",category:"Más ofertas locales",description:"Estamos preparando nuevas promociones de emprendimientos de Ibarra.",image:"/ibarra-hero.png",slug:"",subcategories:[]}];
export default function Promotions(){const [index,setIndex]=useState(0);const [items,setItems]=useState(fallback);useEffect(()=>{let active=true;async function load(){const {data}=await supabase.from("promotions").select("id,title,description,image,business_id,businesses(name,slug,category,city,image)").order("created_at",{ascending:false}).limit(3);if(active&&data?.length){const real=data.map((p:any)=>({name:p.businesses?.name||"Emprendimiento local",category:p.businesses?.category||"Oferta local",description:p.description||p.title||"Promoción disponible",image:p.image||p.businesses?.image||"/ibarra-hero.png",slug:p.businesses?.slug||"",subcategories:[p.title||"Oferta"]}));setItems(real.concat(fallback.slice(real.length)))}}void load();return()=>{active=false}},[]);return <section className="bg-[#fffdf9] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[.25em] text-[#891C20]">Promociones</span><h2 className="mt-3 text-4xl font-black text-[#342821]">Ofertas disponibles</h2><p className="mt-3 text-[#75685f]">Promociones activas de los emprendimientos registrados.</p></div><div className="flex items-center gap-2"><button onClick={()=>setIndex(i=>(i-1+items.length)%items.length)} className="grid h-11 w-11 place-items-center rounded-full border border-[#ead6d0] bg-white text-[#891C20]" aria-label="Oferta anterior"><ChevronLeft size={20}/></button><button onClick={()=>setIndex(i=>(i+1)%items.length)} className="grid h-11 w-11 place-items-center rounded-full border border-[#ead6d0] bg-white text-[#891C20]" aria-label="Siguiente oferta"><ChevronRight size={20}/></button><Link href="/promociones" className="hidden rounded-full border border-[#ead6d0] px-5 py-3 text-sm font-bold text-[#6f1519] hover:bg-[#f4e7d9] md:block">Ver todas →</Link></div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{items.map((_,offset)=>{const card=items[(index+offset)%items.length];return card.slug?<BusinessCard key={offset} name={card.name} category={card.category} description={card.description} image={card.image} location="Ibarra" promotion verified premium={false} slug={card.slug} subcategories={card.subcategories} rating={5} favorites={0}/>:<article key={offset} className="flex min-h-[410px] flex-col justify-center rounded-[28px] border border-dashed border-[#d8b9bd] bg-[#faf0eb] p-7"><span className="w-fit rounded-full bg-[#f2dfe0] px-3 py-1 text-xs font-black uppercase tracking-wider text-[#891C20]">Próximamente</span><h3 className="mt-5 text-2xl font-black text-[#32262b]">Habrá más ofertas</h3><p className="mt-4 leading-7 text-[#6d5960]">{card.description}</p><Link href="/auth/register" className="mt-6 inline-flex w-fit rounded-full bg-[#891C20] px-5 py-3 text-sm font-bold text-white">Registrar mi emprendimiento</Link></article>})}</div></div></section>}
