import Link from "next/link";
import { Heart, MapPin, Star, BadgeCheck } from "lucide-react";

type Props = { name: string; category: string; description?: string; image: string; logo?: string; location: string; verified?: boolean; premium?: boolean; promotion?: boolean; isNew?: boolean; slug?: string; subcategories?: string[]; rating?: number | null; favorites?: number | null };

export default function BusinessCard({ name, category, description, image, location, verified, premium, promotion, isNew, slug, subcategories = [], rating = 5, favorites = 0 }: Props) {
  const href = slug ? `/emprendedores/${slug}` : "/emprendedores";
  const stars = Math.max(0, Math.min(5, Math.round(rating || 5)));
  return <article className="group overflow-hidden rounded-[28px] border border-[#eadbca] bg-[#fffdf9] shadow-[0_12px_40px_rgba(105,72,45,.08)] hover:-translate-y-1 hover:shadow-[0_18px_48px_rgba(105,72,45,.14)]">
    <div className="relative h-56 overflow-hidden"><img src={image} alt={name} className="h-full w-full object-cover group-hover:scale-105"/><div className="absolute inset-x-4 top-4 flex justify-between gap-2">{verified ? <span className="flex items-center gap-1 rounded-full bg-[#fffdf9]/95 px-3 py-1 text-xs font-bold text-[#6c7d68]"><BadgeCheck size={14}/> Verificado</span> : <span/>}<div className="flex gap-2">{premium && <span className="rounded-full bg-[#891C20] px-3 py-1 text-xs font-bold text-white">Premium</span>}{isNew && <span className="rounded-full bg-[#6c7d68] px-3 py-1 text-xs font-bold text-white">Nuevo</span>}</div></div></div>
    <div className="p-6"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black uppercase tracking-wider text-[#891C20]">{category}</span>{promotion && <span className="rounded-full bg-[#f4e7d9] px-2 py-1 text-xs font-bold text-[#6f1519]">Oferta</span>}</div><h3 className="mt-2 text-2xl font-black text-[#342821]">{name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#75685f]">{description || "Conoce este emprendimiento local y sus novedades."}</p>{subcategories.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{subcategories.slice(0, 4).map((item) => <span key={item} className="rounded-full bg-[#f4e7d9] px-2.5 py-1 text-[11px] font-semibold text-[#6f1519]">{item}</span>)}</div>}<p className="mt-4 flex items-center gap-1 text-sm text-[#75685f]"><MapPin size={15}/> {location}</p><div className="mt-4 flex items-center justify-between"><span className="flex items-center gap-1 text-sm font-bold text-[#c6924b]" aria-label={`${stars} de 5 estrellas`}>{Array.from({length: 5}).map((_, index) => <Star key={index} size={15} fill={index < stars ? "currentColor" : "none"}/>)}<span className="ml-1 text-[#75685f]">{(rating || 5).toFixed(1)}</span></span><span className="flex items-center gap-1 text-sm text-[#75685f]"><Heart size={16} className="text-[#891C20]"/> {favorites || 0}</span></div><Link href={href} className="mt-6 block w-full rounded-full bg-[#891C20] py-3 text-center text-sm font-bold text-white hover:bg-[#6f1519]">Ver emprendimiento</Link></div>
  </article>;
}
